package utils

const (
	E_not_found                       = "not_found"
	E_not_found_partner_registration  = "not_found_partner_registration"
	E_user_existed                    = "user_existed"
	E_user_not_existed                = "user_not_existed"
	E_not_found_user_id               = "not_found_user_id"
	E_internal_error                  = "internal errors"
	E_internal_server_error           = "internal_server_errors"
	E_not_found_id                    = "not_found_id"
	E_invalid_state                   = "invalid_state"
	E_can_not_insert                  = "can_not_insert"
	E_can_not_update                  = "can_not_update"
	E_can_not_delete                  = "can_not_delete"
	E_not_found_role_id               = "not_found_role_id"
	E_invalid_token                   = "invalid_token"
	E_invalid_sigature                = "invalid_signature"
	E_not_found_username              = "not_found_username"
	E_username_is_incorrect           = "username_is_incorrect"
	E_password_is_incorrect           = "password_is_incorrect"
	E_not_found_password              = "not_found_password"
	E_not_found_name                  = "not_found_name"
	E_not_found_address               = "not_found_address"
	E_not_found_province              = "not_found_province"
	E_not_found_district              = "not_found_district"
	E_not_found_ward                  = "not_found_ward"
	E_invalid_phone_number            = "invalid_phone_number"
	E_invalid_email                   = "invalid_email"
	E_invalid_otp                     = "invalid_otp"
	E_invalid_password                = "invalid_password"
	E_invalid_username                = "invalid_username"
	E_verify_otp_incorrect            = "verify_otp_incorrect"
	E_not_found_user                  = "not_found_user"
	E_account_not_activated           = "account_not_activated"
	E_email_activated                 = "email_activated"
	E_invalid_address                 = "invalid_address"
	E_invalid_fullname                = "invalid_fullname"
	E_invalid_user_id                 = "invalid_user_id"
	E_invalid_partner_id              = "invalid_partner_id"
	E_invalid_id                      = "invalid_id"
	E_invalid_store                   = "invalid_store"
	E_can_not_insert_partner          = "can_not_insert_partner"
	E_invalid_state_for_sending_email = "invalid_state_for_sending_email"
	E_can_not_insert_store            = "can_not_insert_store"
	E_already_partner                 = "already_partner"
	E_seller_application_pending      = "seller_application_pending"
)
